### ISSUE TITLE
inserting GRD and SLC scenes into the same database can wrongly trigger `check_acquisition_completeness`

### ISSUE THREAD

**Issue by maawoo** [SAR-ARD/S1_NRB#111]
See https://github.com/johntruckenbrodt/pyroSAR/issues/251

In the example, the scene `S1B_IW_SLC__1SDV_20211114T190431_20211114T190501_029588_0387F4_83FA.zip` is not registered regularly into the database, which then results in `check_acquisition_completeness` raising an error because of a missing predecessor scene.

**Comment by johntruckenbrodt** [comment]
I think for the time being it is best to separate SLCs and GRDs into different databases. See comment in https://github.com/johntruckenbrodt/pyroSAR/issues/251. I hope that doesn't cause too much trouble for you.

**Comment by johntruckenbrodt** [comment]
This has been fixed in https://github.com/johntruckenbrodt/pyroSAR/pull/256. The issue can be closed once a new version of pyroSAR has been released and set as dependency in S1_NRB.

**Comment by maawoo** [comment]
https://github.com/SAR-ARD/S1_NRB/pull/145
