### ISSUE TITLE
renaming to accomodate ORB product

### ISSUE THREAD

**Issue by johntruckenbrodt** [SAR-ARD/S1_NRB#114]
Several names of configuration parameters and variable names are specific to NRB and should be renamed to something more universal to apply to ORB as well (before potentially renaming the whole repository). Here's a first list, to be implemented after a more thorough check:
- `S1_NRB.metadata.mapping`:
  - `NRB_PATTERN` -> `ARD_PATTERN` | `RB_PATTERN` | `NRB_PATTERN` + `ORB_PATTERN`?
  - `ORB_MAP` -> `OSV_MAP`
- `config.ini`:
  - `nrb_dir` -> `ard_dir` | `rb_dir`?
  - `rtc_dir` -> `sar_dir`?
  - `mode`: `all` + `rtc` + `nrb` -> `all` + `sar` + `ard`?

**Comment by maawoo** [comment]
+1 on the following:

- `NRB_PATTERN` -> `ARD_PATTERN`
- `ORB_MAP` -> `OSV_MAP`
- `nrb_dir` -> `ard_dir`
- `rtc_dir` -> `sar_dir` (haven't had any other ideas yet)
- `mode`: `all` + `sar` + `ard`
