### ISSUE TITLE
STAC Item-Assets: Differentiate between Noise Power assets in asset title

### ISSUE THREAD

**Issue by jonas-eberle** [SAR-ARD/S1_NRB#118]
I have put some data processed recently by @johntruckenbrodt into our STAC catalogue. I observed that there are two assets with the same title "Noise Power". When visualizing the items in the STAC Browser, a user cannot identify the difference between both assets, see following screenshot. 

![image](https://github.com/SAR-ARD/S1_NRB/assets/2070954/33c0adfc-89b7-40aa-ab7b-88573322cd82)

I guess this happens according to the following code: 
https://github.com/SAR-ARD/S1_NRB/blob/1bf2e6e9560bdef5daf459c585a8f4f7c112a7c5/S1_NRB/metadata/mapping.py#L145-L148

**Comment by maawoo** [comment]
Thank you for reporting this, Jonas!

The asset keys are renamed according to the polarization later on: 
https://github.com/SAR-ARD/S1_NRB/blob/1bf2e6e9560bdef5daf459c585a8f4f7c112a7c5/S1_NRB/metadata/stac.py#L243-L247

This should also adjust the asset title to avoid this problem you observed in STAC Browser. I'll include this fix in #117

**Comment by johntruckenbrodt** [comment]
Thanks @jonas-eberle for reporting and @maawoo for offering to fix this. This is inconvenient but I think at least not too major. Differentiation in xarray should still be possible.

**Comment by jonas-eberle** [comment]
Yes, asset key is not an issue (this is fine) and thus it works with xarray. Could also be solved by adding the asset key in the STAC browser visualization, but there might be other tools that also make use of the asset title.

**Comment by johntruckenbrodt** [comment]
True, it should be fixed to avoid complications when working with the product in any way. I can think something up to modify the dataset once I am back from vacation.
