### ISSUE TITLE
Invalid dates in STAC metadata

### ISSUE THREAD

**Issue by jonas-eberle** [SAR-ARD/S1_NRB#119]
When validating STAC items, I have found invalid dates, especially in the assets (`created`). 

https://staclint.com/ reports the following: 

```
Invalid STAC: ValidationError
Error Message: '2023-06-11T22:11:02.808462' does not match '(\\+00:00|Z)$'. Error is in assets -> vv-g-lin -> created

Schema: https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json
Version: 1.0.0
```
`+00:00` or `Z` is missing at the end. 

Related source code for the assets (but in may appear in other parts as well):
https://github.com/SAR-ARD/S1_NRB/blob/1bf2e6e9560bdef5daf459c585a8f4f7c112a7c5/S1_NRB/metadata/stac.py#L218C27-L218C86

**Comment by johntruckenbrodt** [comment]
Thanks @jonas-eberle
