### ISSUE TITLE
"mean of empty slice" error during ENL computation

### ISSUE THREAD

**Issue by johntruckenbrodt** [SAR-ARD/S1_NRB#125]
Just got this error:
```
S1_NRB\metadata\extract.py:596: RuntimeWarning: Mean of empty slice
  _mean = np.nanmean(blocks, axis=(1, 3))
numpy\lib\nanfunctions.py:1872: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
S1A_IW_GRDH_1SDV_20230101T183417_20230101T183446_046594_05957D_40AA.xml
```

**Comment by maawoo** [comment]
Thanks for reporting this, @johntruckenbrodt! I wouldn't consider this a bug as the calculation of blockwise ENL still works as intended and nodata areas are correctly filled with `np.nan`. This tile, for example, is not fully covered and produces the same warnings: 

![image](https://github.com/SAR-ARD/S1_NRB/assets/56583917/8b0876c0-0c5a-4c35-bedd-9abf5721d8dc)
(High ENL values as this is processed from Stripmap mode)

The current implementation is not perfect but it does the job while still being quite performant. I have worked on possible improvements yesterday, including the usage of numpy `stride_tricks` (e.g., using a solution such as [skimage.util.view_as_blocks](https://github.com/scikit-image/scikit-image/blob/main/skimage/util/shape.py#L8-L94)) and simple for-loops accelerated by [numba](https://numba.pydata.org/). Both directions are not easy to do right and might create new problems. 

I have not come to a good conclusion but I might as well just miss something obvious? At the moment I would consider to just silence these particular warnings and leave the implementation as is. What do you think?

**Comment by johntruckenbrodt** [comment]
Hi @maawoo. Thanks for looking into this and explaining the details. If you see a way of getting around the warning with a test condition that would of course be better but just silencing the warning will also do. No need to spend more time on this.

**Comment by maawoo** [comment]
I just had another idea for a test condition but that didn't work. I'll just silence them. 

The behavior is expected and mentioned in the docstrings of various nan-functions of numpy (e.g., [`numpy.nanmean`](https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html): _"For all-NaN slices, NaN is returned and a RuntimeWarning is raised."_ ). Furthermore, [here](https://github.com/scipy/scipy/pull/18394#issuecomment-1552685843) is more context from a scipy developer.
