### ISSUE TITLE
Look Direction Image not calculated for all swaths (SLC)

### ISSUE THREAD

**Issue by maawoo** [SAR-ARD/S1_NRB#130]
![image](https://github.com/SAR-ARD/S1_NRB/assets/56583917/030d55e3-e28e-4518-9baf-3820f23468da)

**Comment by johntruckenbrodt** [comment]
I only had GRD in mind when developing this since it is only needed for the ORB product. Of ocurse SLC needs to be supported as well though. I'll look into it.
