### ISSUE TITLE
VRTs as STAC assets

### ISSUE THREAD

**Issue by johntruckenbrodt** [SAR-ARD/S1_NRB#51]
Currently only the COG files are registered as STAC assets in the metadata. It would be great if the VRT files (for log scaling and sigma nought computation) could also be listed here and further be utilized with e.g. xarray. 
@maawoo do you know whether this is generally possible?

**Comment by maawoo** [comment]
I had this in my mind at some point as well. Just did a quick check by manually adding the `vh_g_log` VRT as an asset and accessing it via stackstac. It works quite well as far as I can see. Only issue is the scale 10 factor in the VRT. But this will probably be resolved after I reprocess the product and include the changes you made recently (#52).

I'll prepare a PR to include VRT assets today.

**Comment by johntruckenbrodt** [comment]
Fantastic. I also did a quick test and it worked fine for me too. I was not quite sure what best to put for the file type and size though. There is no [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml) entry for VRTs. If one puts something like `text/xml` it is not recognized as an image asset by stackstac. `image/tiff` is of course not really correct but works. Also, I am wondering whether the file size should be that of the actual VRT text file or the size of the actual asset, which is a full size image file. Any experiences on that?
Thanks a lot for offering to create a PR, this is a great addition.

**Comment by johntruckenbrodt** [comment]
Oh, and the recent change of the pixel function does work flawlessly with stackstac/xarray.

**Comment by maawoo** [comment]
For now I'd just use the same file type as for the measurement tifs and the actual file size.
