### ISSUE TITLE
gaps in data takes

### ISSUE THREAD

**Issue by johntruckenbrodt** [SAR-ARD/S1_NRB#93]
It can happen that some scenes are not made available resulting in gaps in the data take:
![image](https://github.com/SAR-ARD/S1_NRB/assets/18419439/3ed96ad1-3368-4c83-8e04-e907649347ac)

In the example above (S1A IW GRD on 2022-09-17) once scene is missing, which currently results in the following error:
```
RuntimeError: missing the following scenes:
 - successor acquisition for scene S1A_IW_GRDH_1SDV_20220917T052551_20220917T052616_045040_0561A9_415F.SAFE
 - predecessor acquisition for scene S1A_IW_GRDH_1SDV_20220917T052641_20220917T052706_045040_0561A9_C5D8.SAFE
```
This error is intended because the processor only sees what is available locally and rightfully complains that the scene is missing. If the scene would indeed only be missing locally, processing the two listed scenes would result in incomplete NRB tiles.  

I assume some mechanism is needed to check an online database whether the scene has ever been made available and only raise an error if it has not.

**Comment by maawoo** [comment]
Looks oddly familiar: https://github.com/opera-adt/s1-reader/issues/117#issuecomment-1561969742
